[build]
builder = "nixpacks"
buildCommand = "cd frontend && npm install && npm run build"

[deploy]
startCommand = "cd backend && npm install && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production" 