[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
PORT = "8080"
ALLOWED_DOMAINS = "localhost:3000, sparkifyai.com,thilakreddy.com"