[build]
builder = "docker"
buildCommand = "docker build -t my-app ."

[deploy]
startCommand = "docker run -p 8080:8080 my-app"
healthcheckPath = "/"
healthcheckTimeout = 100

[env]
NODE_ENV = "production"
PORT = "8080"
ALLOWED_DOMAINS = "localhost:3000, sparkifyai.com,thilakreddy.com"